from api.views.all_users import AllUsers
from api.views.friend_break import FriendBreak
from api.views.friend_info import FriendInfo
from api.views.friend_request_apply import FriendRequestApply
from api.views.friend_request_create import FriendRequestCreate
from api.views.friend_request_delete import FriendRequestDelete
from api.views.friend_request_deny import FriendRequestDeny
from api.views.friend_status import FriendStatus
from api.views.get_user import GetUser
from api.views.register_user import RegisterUser
from api.views.schema import SchemaApiView
